title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: small
          redirectiontext:
            label: Texte du lien de redirection
            type: text
            width: 1/2
            help: Texte à afficher sur le lien qui ramène à la page d'accueil. Si tu ne veux pas de lien, ne remplis pas de champ!
          

  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

